version: "3"

services:   
  fastapi:
    build:
        context: .
        dockerfile: ./fastapi_service/Dockerfile
    environment:
      - USER=${DAGSHUB_USER}
      - PASSWORD=${DAGSHUB_PASSWORD}
      - TOKEN=${DAGSHUB_TOKEN}
      - URI=${DAGSHUB_URI}
      - NAME_MODEL=${DAGSHUB_NAME_MODEL}
      - VERSION_MODEL=${DAGSHUB_VERSION_MODEL}
    ports:
      - 80:80
    restart: always