version: "3"

services:   
  fastapi:
    build:
        context: .
        dockerfile: ./fastapi_service/Dockerfile
    environment:
      - TOKEN=${TOKEN}
    ports:
      - 80:80
    restart: always